# name: Price Check

# on:
#   schedule:
#     - cron: "0 * * * *"
#   workflow_dispatch:

# jobs:
#   run-script:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install dependencies
#         run: pip install requests beautifulsoup4

#       # Restore seen.txt from cache
#       - name: Restore seen cache
#         uses: actions/cache/restore@v4
#         with:
#           path: seen.txt
#           key: seen-cache

#       - name: Run script
#         run: python check_price.py
#         env:
#           TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
#           TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

#       # Save updated seen.txt back to cache
#       - name: Save seen cache
#         uses: actions/cache/save@v4
#         with:
#           path: seen.txt
#           key: seen-cache-${{ github.run_id }}
